baseURL = "https://awstechshift.com/"
disablePathToLower = true
languageCode = "en-us"
title = "AWS Techshift Modernise"
theme = "docter"

[params]
  # the name of your project and a link back to the home page
  home = "AWS Techshift"
  # A small snippet of text above the sidebar:
  subtitle = "Modernise"

  author = "Amazon Web Services"
  author_url= "https://aws.amazon.com"

  # Point readers to your repo and invite them to edit pages 
  repo_host = "Github"
  repo = "https://github.com/richarvey/techshift-modernise"

  # Add a reference to a logo, which will appear in the top right
  logourl = "/img/techshift.png"
  logoalt = "AWS Techshift"

  # Mention your hosting provider 
  hosted_on = "Amazon S3"
  hosted_on_url= "https://aws.amazon.com/s3"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["post"]

  disableInlineCopyToClipBoard = false
